# Split data

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

x, y = np.arange(20).reshape((10, 2)), np.arange(10)

print('before splitting......')

print(f"x: {x}\n")
print(f"y: {y}\n")

print("shape of x: {x.shape}")
print("shape of y: {y.shape}\n")

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
print('after splitting......')

print(f"x_train: {x_train}\n")
print(f"x_test: {x_test}\n")

print(f"y_train: {y_train}\n")
print(f"y_test: {y_test}\n")

before splitting......
x: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

y: [0 1 2 3 4 5 6 7 8 9]

shape of x: {x.shape}
shape of y: {y.shape}

after splitting......
x_train: [[ 2  3]
 [ 4  5]
 [14 15]
 [16 17]
 [ 8  9]
 [ 0  1]
 [18 19]]

x_test: [[12 13]
 [10 11]
 [ 6  7]]

y_train: [1 2 7 8 4 0 9]

y_test: [6 5 3]



# Preprocessing Data

In [11]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 100., -1.,  2.],
                    [ 900.,  0.,  0.],
                    [ 200.,  1., -1.]])

scaler = preprocessing.StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

print("after standardiztion......")
print(f'x_train: {x_train}')


print("\napply same mean and std to new data(test data)")
x_test = np.array([[-1., 1., 0.]])
x_test = scaler.transform(x_test)
print(f'x_test:\n {x_test}')

after standardiztion......
x_train: [[-0.84292723 -1.22474487  1.33630621]
 [ 1.40487872  0.         -0.26726124]
 [-0.56195149  1.22474487 -1.06904497]]

apply same mean and std to new data(test data)
x_test:
 [[-1.12671273  1.22474487 -0.26726124]]


In [7]:
x_train = np.array([[ 100., -1.,  2.],
                    [ 900.,  0.,  0.],
                    [ 200.,  1., -1.]])

x_train = preprocessing.StandardScaler().fit_transform(x_train)

print("after standardiztion......")
print(f'x_train:\n {x_train}')

after standardiztion......
x_train:
 [[-0.84292723 -1.22474487  1.33630621]
 [ 1.40487872  0.         -0.26726124]
 [-0.56195149  1.22474487 -1.06904497]]
